### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by chymian** [arminus/ObsidianReceiver#4]
LiveSync is working nicley over a couple of devices.
Now I wanted to set up the OBSReceiver and get `Internal Server Error` while testing it.

any hints what I'm missing?

### Setup::
obsreceiver runs on a LXC remote container.
public access is via a HAProxy (same as LiveSync CouchhDB)
testing localy with curl or remorly gives the same error:
```
curl  http://YYYYYY:XXXXXXXX@localhost:5985
"Call this with a PUT request on /obsput and your content in the body"

curl --location --request PUT 'http://YYYYYY:XXXXXX@localhost:5985/obsput?timestamp=true&list=true' --header 'Content-Type: text/plain' --data-raw 'Test from cUrl'
Internal Server Error
```
### Config-file:
```
cat obsidian_conf/CouchDB.yaml
couchdb:
  dbname: "obsidian_numbero-uno"
  username: "YYYYYYY"
  password: "XXXXXXX"
  # CouchDB DB address part, e.g. https://couchdb.my.domain.com/obs/"
url: "https://cdb.yyy.xxx:5984/"
obsidian:
  # the fully qualified name of the "receiver" .md file, e.g. 0-WorkInProgress/IncomingData.md
  target_doc_id: "Cards/Boats/IncomingData.md"
  timestamp_format: "%Y-%m-%d %H:%M:%S"
```

```bash
SERVER_PORT=5985
podman run --restart always -d --name obsreceiver  --env SERVER_PORT=$OBS_SERVER_PORT  \
 -p $OBS_SERVER_PORT:$OBS_SERVER_PORT  -v /$(pwd)/obsidian_conf:/root/obsidian_conf obsreceiver:latest
```

### Error logged by docker:
```
ontent: Test from cUrl
INFO:     172.16.16.1:49138 - "PUT /obsput?timestamp=true&list=true HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/root/./server.py", line 47, in obsput
    obsCdb = OBSCouchDB(doc_id)
  File "/root/./OBSCouchDB.py", line 66, in __init__
    couchdb_url = config["couchdb"]["url"]      # CouchDB DB address, e.g. https://couchdb.my.domain.com/obs/
KeyError: 'url'
```

**Comment by arminus** [comment]
Looks like the url parameter in your config yml is not properly indented. Compare that with [CouchDB.yaml.dist](https://github.com/arminus/ObsidianReceiver/tree/master/obsidian_conf/CouchDB.yaml.dist) please.

**Comment by chymian** [comment]
your right. thx
and thanks for this nice pice of software.
